#!/usr/bin/env python3
"""Generate schema/status.schema.json from moatlib.

Generated rather than hand-written so the schema and the code that enforces it
cannot disagree. A schema nothing regenerates drifts silently, and a stale one is
worse than none: it rejects data that is actually correct.

    python3 utils/gen_schema.py            # write the schema
    python3 utils/gen_schema.py --check    # fail if it is out of date (CI)
"""

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import moatlib as m

OUT = m.REPO_ROOT / "schema" / "status.schema.json"


def build():
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://github.com/AMD-Ecosystem/moat/schema/status.schema.json",
        "title": "MOAT per-project status",
        "$comment": "GENERATED by utils/gen_schema.py from moatlib -- do not hand-edit.",
        "type": "object",
        "required": ["schema_version", "name", "upstream_url", "fork_default_branch",
                     "priority", "ext_type", "platforms"],
        "properties": {
            # Both versions while the migration runs, matching validate_status --
            # a const here would fail every record not yet stamped.
            "schema_version": {"enum": list(m.READABLE_SCHEMA_VERSIONS)},
            "name": {"type": "string"},
            "upstream_url": {"type": "string"},
            # GitHub's numeric repo id, which survives a rename or an org transfer.
            # upstream_url does not: FlashRT moved from LiangSu8899 to the
            # flashrt-project org and the recorded URL became a name nobody uses.
            # Adoption is matched on this so a transferred project cannot re-enter
            # discovery looking unclaimed.
            "upstream_repo_id": {"type": ["integer", "null"]},
            "fork_url": {"type": ["string", "null"]},
            "fork_default_branch": {"type": "string"},
            "fork_branch": {"type": "string",
                            "description": "port branch when it is not moat-port"},
            "priority": {"type": "number"},
            # Free-form, not an enum. The three canonical values (cmake,
            # torch-extension, unknown) drive Strategy A vs B and cover most
            # projects, but the field records what the build actually IS, and
            # reality includes meson, qmake, go-cgo-driver-api, pccm-codegen and
            # others. The old hand-written schema fixed this at three values,
            # which every such project would have failed had anything run it.
            "ext_type": {"type": "string", "minLength": 1},
            "adopted_at": {"type": ["string", "null"]},
            "updated_at": {"type": ["string", "null"]},
            "head_sha": {"type": ["string", "null"],
                         "description": "current fork branch HEAD"},
            "depends_on": {"type": "array", "items": {"type": "string"}},
            "on_hold": {"type": "boolean"},
            "on_hold_reason": {"type": ["string", "null"]},
            # Fork-write lock. Absent/null means no arch is writing to the fork, so
            # any arch may validate. Takeover is a human decision, not a timeout,
            # which is why there is no expiry field.
            "porting": {
                "type": ["object", "null"],
                "required": ["arch", "since"],
                "properties": {
                    "arch": {"type": "string", "pattern": m.PLATFORM_RE.pattern},
                    "since": {"type": "string"},
                },
            },
            # Explicit release marker naming the acquisition it ended (arch +
            # since). The merge driver drops a lock only when a marker matches
            # it; without this, "released" and "never saw the lock" were told
            # apart by timestamp inference, which erased concurrent acquisitions.
            "porting_released": {
                "type": ["object", "null"],
                "required": ["arch", "since", "at"],
                "properties": {
                    "arch": {"type": "string", "pattern": m.PLATFORM_RE.pattern},
                    "since": {"type": "string"},
                    "at": {"type": "string"},
                },
            },
            # Gate waivers. Only gates listed waivable in config/arches.toml may be
            # waived, and only with maintainer approval: a record lacking approved_by
            # satisfies nothing, so an agent cannot self-certify past a gate.
            "waivers": {
                "type": "object",
                "propertyNames": {"enum": sorted(m.WAIVABLE_GATES)},
                "additionalProperties": {
                    "type": "object",
                    "required": ["reason"],
                    "properties": {
                        "reason": {"type": "string", "minLength": 1},
                        # When an agent made the case, as against when a maintainer
                        # approved it (`at`). Both are kept: the gap between them is
                        # how long a finished port sat waiting on one decision.
                        "suggested_at": {"type": "string"},
                        "approved_by": {"type": "string", "minLength": 1},
                        "at": {"type": "string"},
                        # A refusal is an answer too, and is kept rather than deleting
                        # the suggestion: the next agent to hit the same wall needs to
                        # know it was asked, answered, and what to look at instead.
                        "refused_by": {"type": "string", "minLength": 1},
                        "refused_at": {"type": "string"},
                        "refused_note": {"type": "string", "minLength": 1},
                    },
                },
            },
            # The licence as READ from the repo -- a fact any agent may establish, and
            # the input to license_tier()/license_gate(). Distinct from the clearance
            # below, which is a person's DECISION about that fact. Both live here so
            # one file answers "may this go upstream on licence grounds?".
            "license_spdx": {"type": ["string", "null"]},
            # Intake's recommendation, never its decision. A verdict of "decline"
            # says what intake would choose; dispositions.json records what a person
            # actually chose, and only that gates anything.
            "intake": {
                "type": ["object", "null"],
                "required": ["verdict", "summary"],
                "properties": {
                    "verdict": {"enum": list(m.INTAKE_VERDICTS)},
                    "reason": {"type": ["string", "null"]},
                    "duplicate_effort": {"type": ["string", "null"]},
                    "viable": {"type": ["boolean", "null"]},
                    "summary": {"type": "string"},
                    "at": {"type": "string"},
                    # The person's answer to the recommendation above. Recorded
                    # because the gap between deciding to fork and the fork existing
                    # is unbounded, and the queue otherwise reverts to arguing the
                    # recommendation -- worst exactly where they disagree.
                    "decided": {
                        "type": ["object", "null"],
                        "required": ["choice", "by", "at"],
                        "properties": {
                            "choice": {"enum": ["fork", "decline"]},
                            "by": {"type": "string", "minLength": 1},
                            "at": {"type": "string"},
                            "note": {"type": "string"},
                        },
                    },
                },
            },
            # Permission to offer a tier 3/4 project upstream; tiers 1-2 need none.
            # Like a gate waiver, a record without approved_by satisfies nothing, so
            # an agent cannot self-certify past it, and it clears ONE project rather
            # than its whole tier.
            "license_clearance": {
                "type": ["object", "null"],
                "required": ["approved_by", "at"],
                "properties": {
                    "approved_by": {"type": "string", "minLength": 1},
                    "at": {"type": "string"},
                    "tier": {"type": "integer"},
                    "note": {"type": "string"},
                },
            },
            # The upstream PR: one project-level fact. It is deliberately NOT an arch
            # state -- opening a PR changes nothing any arch validated.
            "pr_state": {"enum": list(m.PR_STATES)},
            "pr_url": {"type": "string"},
            "pr_number": {"type": "integer"},
            "pr_opened_at": {"type": "string"},
            "pr_merged_at": {"type": "string"},
            "pr_closed_at": {"type": "string"},
            "pr_closed_note": {"type": "string"},
            # What the open upstream PR shows. While a fix round is staged,
            # head_sha runs ahead of this on the staging branch; only the trusted
            # merge path (upstream.py --merge-fix) advances it.
            "published_sha": {"type": ["string", "null"]},
            # A maintainer-requested fix round in flight: the staging branch cut
            # from the published tip, and the fork review PR where a person
            # approves the delta. Cleared when the round merges.
            "fix": {
                "type": ["object", "null"],
                "required": ["branch", "base_sha"],
                "properties": {
                    "branch": {"type": "string", "minLength": 1},
                    "base_sha": {"type": "string", "minLength": 1},
                    "review_pr": {"type": ["string", "null"]},
                    "opened_at": {"type": "string"},
                },
            },
            "fix_merged_at": {"type": "string"},
            # The review PR on our own fork: where a maintainer sees the code, title
            # and body together, and approves once.
            "review_pr": {"type": "string"},
            # Snapshot of that approval. It records the reviewed head and a hash of
            # the title+body, so an unattended job can prove what it is about to
            # publish is what was approved. Either changing voids it, which is why a
            # digest is stored rather than a bare flag.
            "pr_approval": {
                "type": ["object", "null"],
                "required": ["approved_by", "at", "head_sha", "content_sha256"],
                "properties": {
                    "approved_by": {"type": "string", "minLength": 1},
                    "at": {"type": "string"},
                    "head_sha": {"type": "string"},
                    "content_sha256": {"type": "string", "pattern": "^[0-9a-f]{64}$"},
                    "review_pr": {"type": "string"},
                },
            },
            # Where the PORT is. One fork, one answer -- as against platforms[arch],
            # which records only what a given GPU proved. Not required: records
            # written before this field existed are still readable while they are
            # migrated (see READABLE_SCHEMA_VERSIONS).
            "stage": {"enum": sorted(m.STAGE_STATES)},
            # A person's verdict that the codebase cannot be ported at all, which is
            # what `stage: not-portable` stands on. Like a gate waiver and a licence
            # clearance, a record without `by` satisfies nothing -- an agent may build
            # the case and may not sign it. An OS that refuses the port is a `windows`
            # waiver instead, and a toolchain defect on one card is a per-arch block.
            "not_portable": {
                "type": ["object", "null"],
                "required": ["reason", "by", "at"],
                "properties": {
                    "reason": {"type": "string", "minLength": 1},
                    "by": {"type": "string", "minLength": 1},
                    "at": {"type": "string"},
                },
            },
            # Open platform map. A key is any well-formed <os>-<gfx>, checked by
            # shape rather than against a roster, so a host with a new GPU records a
            # validation without a schema change. Absent means "never worked here".
            "platforms": {
                "type": "object",
                "propertyNames": {"pattern": m.PLATFORM_RE.pattern},
                "additionalProperties": {"$ref": "#/$defs/arch"},
            },
        },
        "$defs": {
            # Only what an ARCHITECTURE can record. port-ready and revalidate are
            # derived from (stage, validated_sha, head_sha) and never stored.
            "archstate": {"enum": sorted(m.ARCH_STATES)},
            "arch": {
                "type": "object",
                # `state` is not required: a migrated block holds only what this arch
                # can know, and for an arch that never validated that is `blocked`
                # alone. The project's own progress lives in `stage`.
                "required": ["blocked"],
                "properties": {
                    "state": {"$ref": "#/$defs/archstate"},
                    "blocked": {"type": "boolean"},
                    "blocked_reason": {"type": ["string", "null"]},
                    "validated_sha": {"type": ["string", "null"],
                                      "description": "head this arch last validated"},
                    # The counterpart, and read the same way: a failure is evidence
                    # about ONE commit. Once a fix moves head past it the arch is owed
                    # a validation rather than another porter round, which is derived
                    # from these two shas and never stored (see failure_stands).
                    "failed_sha": {"type": ["string", "null"],
                                   "description": "head this arch last failed to validate"},
                    "pr_url": {"type": ["string", "null"]},
                    "pr_number": {"type": ["number", "null"]},
                    "started_at": {"type": ["string", "null"]},
                    "completed_at": {"type": ["string", "null"]},
                    "updated_at": {"type": ["string", "null"]},
                    "last_agent": {"type": ["string", "null"]},
                    "carry_forward": {"type": "object"},
                    "stats": {"type": "object"},
                },
            },
        },
    }


def main():
    text = json.dumps(build(), indent=2) + "\n"
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print("gen_schema: schema/status.schema.json is out of date "
                  "(run utils/gen_schema.py)", file=sys.stderr)
            return 1
        print("gen_schema: schema is up to date")
        return 0
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(m.REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
